### ISSUE TITLE
panic using example code

### ISSUE THREAD

**Issue by nicks6240** [rafaelespinoza/bart-go#1]
panic: runtime error: invalid memory address or nil pointer dereference

```
package main

import (
	"fmt"

	"github.com/rafaelespinoza/bart-go"
)


func main() {

	c := new(bart.Client)
	var res interface{}
	var err error

	// Use the quick planner to request departure from SF airport to Castro Valley station, at
	// current date, departing now with 2 trips, before & after.
	departure := bart.TripParams{"sfia", "cast", "", "", 2, 2, true}
	res, err = c.RequestDepartures(departure)
	fmt.Println(res, err)
}
```

error

```go run bartalert.go
fetching https://api.bart.gov/api/sched.aspx?a=2&b=2&cmd=depart&dest=cast&json=y&key=MW9S-E7SL-26DU-VV8V&l=1&orig=sfia
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x5efd71]

goroutine 1 [running]:
github.com/rafaelespinoza/bart-go.newGetReq(0xc04206ab10, 0xc0420121c0, 0x6d, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/SkitchN/Documents/goprojects/src/github.com/rafaelespinoza/bart-go/api.go:65 +0xb1```

**Comment by rafaelespinoza** [comment]
Hi, thanks for bringing this up. I suspect the issue is that `res` (or `res.Body`) in the [defer function](https://github.com/rafaelespinoza/bart-go/blob/a7d4561ecbebf9a192638a1c94d33998e423d051/api.go#L65) is empty. I've actually been unable to reproduce the issue, so that's my best guess.

Would you mind telling me:

- what version of go you're running?
- roughly what time of day (and which day of the week) you got the error?

Thanks

**Comment by rafaelespinoza** [comment]
@nicks6240 I've updated the error handling (along with a few other things) in #2. Please give the code another try and let me know if it helps the panic problem you brought up earlier.

**Comment by nicks6240** [comment]
@rafaelespinoza Hi, I tried the new build and this time the error is handled and it's saying the connection was forcefully closed.

Did some troubleshooting and realized it's due to a locked down network requiring a proxy.  Was able to fix, but had to change in the vendored library:
`api.go:28`:
```
var httpClient = getHttpClient()


func getHttpClient() *http.Client {
	proxyHost := "http://proxy-sfo:80"
	proxyURL, _ := url.Parse(proxyHost)
	tr := &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}, Proxy: http.ProxyURL(proxyURL)} // disable SSL integrity check
	return &http.Client{Transport: tr}
}```

**Comment by rafaelespinoza** [comment]
Oh interesting. If this library had something like:

```go
func ReplaceClient(client *http.Client) {
	httpClient = client
}
```

would it solve your problem?

**Comment by nicks6240** [comment]
yes, func or method is ideal.

**Comment by rafaelespinoza** [comment]
A function (`NewClient`) has been added. Feel free to re-open if it still doesn't work.
